Seminar 5
========================================================


```{r}
library(lattice)
#source() #to source function in a seperate file
prepareData <- function(prDat, prDes, luckyGenes){
  geneList <- prDat[luckyGenes,]
  #geneVec <- as.vector (geneList) #change each element of list to a vector
  geneMatrix <- as.matrix(geneList)
  geneVec <- as.vector (t(geneMatrix))
  
  geneName <- rep(luckyGenes , each = 39)
  
  jDat<- data.frame(prDes, gExp = geneVec, geneName)
  return(jDat)
}

makeStripplot <- function(jDat, pch, cex){
  stripplot(gExp ~ devStage | geneName, jDat, group = gType, jitter.data = TRUE, auto.key = TRUE, type = c('p', 'a'), grid = TRUE, pch = pch, cex = cex)
}


prDat <- read.table("/Users/fdorri/Documents/UBC/courses/STAT540/workspace/stat540_2014/examples/photoRec/data/GSE4051_data.tsv")
str(prDat, max.level = 0)
prDes <- readRDS("/Users/fdorri/Documents/UBC/courses/STAT540/workspace/stat540_2014/examples/photoRec/data/GSE4051_design.rds")
str(prDes)

  
(luckyGenes <- c("1419655_at","1438815_at"))
newDat <- prepareData(prDat, prDes, luckyGenes)
str(newDat)

head(newDat)
tail(newDat)
makeStripplot(newDat, pch = 20, cex = 1.3)
```
```{r}
luckyGenes <- c( "1456341_a_at")
newDat <-prepareData(prDat, prDes, luckyGenes)
sub <- subset(newDat,devStage == "P2" | devStage == "4_weeks")
t.test(sub$gExp ~ sub$devStage,var.equal=T)
```

```{r}
luckyGenes <- c( "1438786_a_at")
newDat <-prepareData(prDat, prDes, luckyGenes)
makeStripplot(newDat, pch = 20, cex = 1.3)
mod_1 <- lm(formula = gExp ~ devStage, data = newDat, subset = gType == "wt")
summary(mod_1)
```

```{r}
coef(mod_1)
contrast_M <- matrix(c(0,1,0,-1,0),nrow=1)
(obsDiff <- contrast_M %*% coef(mod_1))
coef(mod_1)
sampMeans <- aggregate(gExp ~ devStage, newDat, FUN = mean,subset = gType == "wt")
sampMeans

with(sampMeans, gExp[devStage == "P2"] - gExp[devStage == "P10"]) #The with( ) function applys an expression to a dataset.
vcov(mod_1) #Returns the variance-covariance matrix of the main parameters of a fitted model object
summary(mod_1)$coefficients[ , "Std. Error"]
sqrt(diag(vcov(mod_1)))
(estSe <- contrast_M %*% vcov(mod_1) %*% t(contrast_M))
(testStat <- obsDiff/estSe)
2 * pt(abs(testStat), df = df.residual(mod_1), lower.tail = FALSE)

```
```{r}

makeStripplot(newDat <- prepareData(prDat, prDes, "1448690_at"), pch = 20, cex = 1.3)
str(newDat)
mod_2 <- lm(formula = gExp ~ gType*devStage, data = newDat) #including the interaction
summary(mod_2)$coef
mod_3 <- lm(formula = gExp ~ gType+devStage, data = newDat) #without interaction
summary(mod_3)$coef
anova(mod_2, mod_3)
```

```{r}
makeStripplot(newDat <- prepareData(prDat, prDes, "1429225_at"), pch = 20, cex = 1.3)
str(newDat)
mod_4 <- lm(formula = gExp ~ gType*devStage, data = newDat) #including the interaction
summary(mod_4)$coef
mod_5 <- lm(formula = gExp ~ gType+devStage, data = newDat) #without interaction
summary(mod_5)$coef
anova(mod_4, mod_5)
```




