

Seminar 4
========================================================

First read the data:
```{r}
library(lattice)
prDat <- read.table("/Users/fdorri/Documents/UBC/courses/STAT540/workspace/stat540_2014/examples/photoRec/data/GSE4051_data.tsv")
str(prDat, max.level = 0)
prDes <- readRDS("/Users/fdorri/Documents/UBC/courses/STAT540/workspace/stat540_2014/examples/photoRec/data/GSE4051_design.rds")
str(prDes)
```
Then, let's extract the data for one gene and put in a data. So first randomly choose a gene:
```{r}
set.seed(987)
(theGene <- sample(1:nrow(prDat), 1))
```
then extract the data for the selected gene:
```{r}
pDat <- data.frame(prDes, gExp = unlist(prDat[theGene, ]))
str(pDat)
```
```{r}
aggregate(gExp ~ gType, pDat, FUN = mean)
stripplot(gType ~ gExp, pDat)
```
```{r}
t.test(gExp ~ gType, pDat)
ttRes <- t.test(gExp ~ gType, pDat)
str(ttRes)
ttRes$statistic
ttRes$p.value
```

```{r}
kDat <- readRDS("/Users/fdorri/Documents/UBC/courses/STAT540/workspace/stat540_2014/examples/photoRec/data/GSE4051_MINI.rds")
kMat <- as.matrix(kDat[c('crabHammer', 'eggBomb', 'poisonFang')])
str(kMat)
median(kMat[ , 1])         # column numbers are mysterious
median(kMat[ , 'eggBomb']) # use names for better code!
apply(kMat, 1, median) # here it means the first dimension!! not the first column :)
apply(kMat, 2, median)
apply(kMat, 2, quantile, probs = 0.5)
apply(kMat, 2, quantile, probs = c(0.25, 0.75))
```

```{r}
colnames(kMat)[apply(kMat, 1, which.min)]
rowSums(kMat) #see also rowSums, colMeans, colSums
all.equal(rowSums(kMat), apply(kMat, 1, sum))
colMeans(kMat)
all.equal(colMeans(kMat), apply(kMat, 2, mean))
jRowSums <- rowSums(prDat)
jRowSums <- apply(prDat, 1, sum)
prMat <- as.matrix(prDat) # must have an actual matrix
jRowSums <- rep(NA, nrow(prDat)) # must initialize a receptacle
for(i in 1:nrow(prDat)) {
   jRowSums[i] <- sum(prMat[i, ])
}
aggregate(eggBomb ~ devStage, kDat, FUN = mean)
aggregate(eggBomb ~ gType * devStage, kDat, FUN = mean)
aggregate(eggBomb ~ gType * devStage, kDat, FUN = range)
keepGenes <- c("1431708_a_at", "1424336_at", "1454696_at",
               "1416119_at", "1432141_x_at", "1429226_at" )
miniDat <- subset(prDat, rownames(prDat) %in% keepGenes)
miniDat <- data.frame(gExp = as.vector(t(as.matrix(miniDat))),
                      gene = factor(rep(rownames(miniDat), each = ncol(miniDat)),
                                    levels = keepGenes))
miniDat <- suppressWarnings(data.frame(prDes, miniDat))
str(miniDat)
stripplot(gType ~ gExp | gene, miniDat,
          scales = list(x = list(relation = "free")),
          group = gType, auto.key = TRUE)
```






