Seminar 6
========================================================

```{r}
library(limma)
library(lattice)

makeStripplot <- function(jDat, pch, cex){
  stripplot(gExp ~ devStage | geneName, jDat, group = gType, jitter.data = TRUE, auto.key = TRUE, type = c('p', 'a'), grid = TRUE, pch = pch, cex = cex)
}
prDat <- read.table("/Users/fdorri/Documents/UBC/courses/STAT540/workspace/stat540_2014/examples/photoRec/data/GSE4051_data.tsv")
str(prDat, max.level = 0)
prDes <- readRDS("/Users/fdorri/Documents/UBC/courses/STAT540/workspace/stat540_2014/examples/photoRec/data/GSE4051_design.rds")
str(prDes)
```
```{r}
m <- 1000
n <- 3
x <- matrix(rnorm(m * n), nrow = m)
obsVars <- apply(x, 1, var)
summary(obsVars)
mean(obsVars < 1/3)
densityplot(~obsVars, n = 200)
```
```{r}
prDes
wtDes <- subset(prDes, gType == "wt")
wtDes
str(wtDes)
wtDat <- subset(prDat, select = prDes$gType == "wt")
str(wtDat, max.level = 0)
wtDesMat <- model.matrix(~devStage, wtDes)
wtDesMat
str(wtDesMat)
```
```{r}
wtFit <- lmFit(wtDat, wtDesMat)
wtEbFit <- eBayes(wtFit)
topTable(wtEbFit)
```
```{r}
topTable(wtEbFit, coef = 2:5)
colnames(coef(wtEbFit))
(dsHits <- topTable(wtEbFit, coef = grep("devStage", colnames(coef(wtEbFit)))))
head(topTable(wtEbFit))
(dsHits <- topTable(wtEbFit[64], coef = grep("devStageP6", colnames(coef(wtEbFit)))))
```

```{r}
# test the effect of developmental stage
p2hit <- topTable(wtEbFit, coef = "devStageP2", 
                  number=nrow(wtDat), sort.by="none")
p10hit <- topTable(wtEbFit, coef = "devStageP10", 
                   number=nrow(wtDat), sort.by="none")

# plot test statistics against one another
smoothScatter(p10hit$t ~ p2hit$t,
       xlab="P2 t-statistic", ylab="P10 t-statistic", xlim=c(-10,10), ylim=c(-10,10) )
# fit a line to the points
myline.fit <- lm(p10hit$t ~ p2hit$t)
abline(myline.fit)
```
```{r}

densityplot(~p10hit$adj.P + p2hit$adj.P, 
            xlab="adjusted p-values",
            plot.points=F,
            scales=list(tck=c(1,0)))

# p-values < 0.001
addmargins(table(p2hit$adj.P<0.001, p10hit$adj.P<0.001,
                 dnn=c("P2", "P10")))

# how many have p-val < 0.00001
addmargins(table(dsHits$adj.P < 0.00001))
p10by <- topTable(wtEbFit, coef = "devStageP10", 
                   number=nrow(wtDat), sort.by="none",
                   adjust.method=c("BY"))
pvals <- data.frame(raw=p10hit$P.Val, 
                    BH=p10hit$adj.P, 
                    BY=p10by$adj.P) 
# BH pvals are larger than raw pvals (as expected)
plot(pvals)
```
```{r}
colnames(wtDesMat)
(cont.matrix <- makeContrasts(P10VsP6 = devStageP10 - devStageP6, fourweeksVsP10 = devStage4_weeks - 
    devStageP10, levels = wtDesMat))
wtFitCont <- contrasts.fit(wtFit, cont.matrix)
wtEbFitCont <- eBayes(wtFitCont)
topHits <- topTable(wtEbFitCont)
#makeStripplot(miniDF(rownames(topHits)[1:4]), pch = 16 , cex= 1.3)
stripplot(gExp ~ devStage | rownames(topHits)[1:4], topHits, group = gType, jitter.data = TRUE, auto.key = TRUE, type = c('p', 'a'), grid = TRUE, pch = 10, cex = 1.3)
```